import React from 'react';
import { useNavigate } from 'react-router-dom';
import { useAuth } from '../../context/AuthContext';
import { Building2, LogOut, MapPin, Phone, Star } from 'lucide-react';

export const BuyerProfile: React.FC = () => {
  const { currentUser, logout } = useAuth();
  const navigate = useNavigate();
  if (!currentUser) return null;
  const handleLogout = async () => { await logout(); navigate('/'); };
  return <div className="min-h-screen bg-slate-50 pb-20"><div className="bg-blue-900 px-4 py-10 text-white"><div className="mx-auto max-w-3xl"><p className="text-xs font-bold uppercase tracking-wider text-blue-200">Buyer Profile</p><h1 className="mt-1 text-3xl font-black">My Account</h1></div></div><div className="mx-auto max-w-3xl -mt-5 px-4"><div className="rounded-3xl border border-slate-200 bg-white p-6 shadow-card sm:p-8"><div className="flex flex-col gap-5 border-b border-slate-100 pb-6 sm:flex-row sm:items-center"><div className="flex h-20 w-20 items-center justify-center rounded-3xl bg-blue-100 text-blue-700"><Building2 className="h-10 w-10" /></div><div className="flex-1"><h2 className="text-2xl font-black text-slate-900">{currentUser.name}</h2><p className="mt-1 text-sm text-slate-500">Buyer · {currentUser.businessType || currentUser.villageOrBusinessName}</p><div className="mt-3 flex flex-wrap gap-4 text-sm font-semibold text-slate-700"><span className="flex items-center gap-1"><MapPin className="h-4 w-4 text-blue-600" />{currentUser.location}</span><span className="flex items-center gap-1"><Phone className="h-4 w-4 text-blue-600" />{currentUser.phone}</span></div></div></div><div className="grid gap-3 py-6 sm:grid-cols-3"><div className="rounded-2xl bg-blue-50 p-4"><p className="text-xs text-slate-500">Rating</p><p className="mt-1 flex items-center gap-1 text-xl font-black"><Star className="h-5 w-5 fill-amber-400 text-amber-400" />{currentUser.rating ?? '—'}</p></div><div className="rounded-2xl bg-slate-50 p-4"><p className="text-xs text-slate-500">Completed purchases</p><p className="mt-1 text-xl font-black">{currentUser.completedOrdersCount}</p></div><div className="rounded-2xl bg-slate-50 p-4"><p className="text-xs text-slate-500">State</p><p className="mt-1 text-xl font-black">{currentUser.state}</p></div></div><button onClick={handleLogout} className="flex w-full items-center justify-center gap-2 rounded-xl border border-red-200 bg-red-50 py-3 font-bold text-red-700 hover:bg-red-100"><LogOut className="h-4 w-4" />Logout</button></div></div></div>;
};
